### ISSUE TITLE
Running speed issue

### ISSUE THREAD

**Issue by ghost** [Atlante1952/Swamp#1]
Hi,

there is an issue with the running speed if stamina mods are in use, if "swamp" is enabled.
The running speed get reduced to walking speed in general like without stamina, and that without being in a swamp biome.

Thats all.

**Comment by atlante01** [comment]
Oh ok, ty i'll try to fix it :p

**Comment by Neuromancer56** [comment]
I'm still seeing this issue, not being able to run/sprint in any biome with any mods when swamp mod is enabled.

**Comment by david-wolgemuth** [comment]
> closed this as completed

I don't see any commits to this repo in the last month?

------

but scanning the codebase,
I'm fairly sure this is the problem here:

https://github.com/AtlanteFr/Swamp/blob/d065840952fb7dba8057ff8365ca88012fa7b3e6/swamp.lua#L104-L114

it is _always_ setting the speed to 1.0,

it should do this **only if the player was previously on a mudblock**,
otherwise it shouldn't do anything at all
